### PR TITLE
Add identifier so open registers can categorise traffic origin

### PR DESCRIPTION
**Pull request by endamccormack**

### CODE REVIEW

**Comment by andyjpb** [comment]
Great work!
What is the .gitignore change?
If you're adding client-id rather than the standard http ua header, can we annotate it with even more information (such as the source file it was called from; that might identify the specific service and not be too sensitive)?

**Review by dankmitchell — APPROVED** [review]
Nice update

**Comment by endamccormack** [comment]
@andyjpb the .gitignore change is just telling git to ignore .idea which is a folder generated by all jetbrains IDE's intellij, pycharm, rubymine etc. which a couple of people on the team use.

**Comment by endamccormack** [comment]
Updated this following a conversation with @samcrang around what would work best for his work with the metrics.

**Comment by samcrang** [comment]
Love it. If/when we start publishing to Rubygems we can add a version or something.

**Comment by andyjpb** [comment]
@endamccormack: Should it be in a separate commit?

**Comment by endamccormack** [comment]
Why yes it should @andyjpb.

**Comment by philandstuff** [comment]
👍

**Pull request merged**
